; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; POPRAWKA: Odkomentuj te flagi, aby włączyć obsługę liczb zmiennoprzecinkowych w printf/sprintf
build_flags = 
	-Wl,-u,vfprintf
	-lprintf_flt
	-lm

; Prędkość monitora portu szeregowego
monitor_speed = 9600

; Konfiguracja debuggera
debug_tool = simavr

; Zależności biblioteczne
; PlatformIO automatycznie pobierze i zainstaluje te biblioteki dla tego projektu
lib_deps = 
    adafruit/RTClib
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    marcoschwartz/LiquidCrystal_I2C
    adafruit/DHT sensor library @ ^1.4.4
    Servo
;    codersbr/TM1637